<?php
require __DIR__.'/auth.php';requireLogin();$uid=(int)$_SESSION['user_id'];
if(($_GET['action']??'')==='download'){
 $u=$db->prepare('SELECT id,name,email,profile_photo,created_at,updated_at FROM users WHERE id=?');$u->execute([$uid]);$user=$u->fetch();
 $q=$db->prepare('SELECT lunch_date,food_item,quantity,notes,meal_type,meal_time,recorded_time,calories,protein,carbs,fat FROM lunches WHERE user_id=? ORDER BY lunch_date,meal_time,id');$q->execute([$uid]);
 $w=$db->prepare('SELECT weight_kg,weight_date,notes,created_at FROM weights WHERE user_id=? ORDER BY weight_date,id');$w->execute([$uid]);
 $payload=['format'=>'Lunch Food Log Backup','version'=>2,'exported_at'=>date('c'),'user'=>$user,'lunches'=>$q->fetchAll(),'weights'=>$w->fetchAll()];
 header('Content-Type: application/json; charset=utf-8');header('Content-Disposition: attachment; filename="lunch-food-log-backup-'.date('Y-m-d').'.json"');echo json_encode($payload,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE);exit;
}
$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verifyCsrf();if(!isset($_FILES['backup'])||$_FILES['backup']['error']!==UPLOAD_ERR_OK){$error='Choose a valid backup JSON file.';}elseif($_FILES['backup']['size']>10*1024*1024){$error='Backup file is too large.';}else{try{$raw=file_get_contents($_FILES['backup']['tmp_name']);$data=json_decode($raw,true,512,JSON_THROW_ON_ERROR);if(($data['format']??'')!=='Lunch Food Log Backup')throw new RuntimeException('This is not a Lunch Food Log backup.');$added=0;$weightsAdded=0;
 foreach(($data['lunches']??[]) as $r){$date=$r['lunch_date']??'';$food=trim((string)($r['food_item']??''));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||$food==='')continue;$chk=$db->prepare('SELECT id FROM lunches WHERE user_id=? AND lunch_date=? AND food_item=? AND meal_type=? AND COALESCE(quantity,\'\')=? LIMIT 1');$chk->execute([$uid,$date,$food,(string)($r['meal_type']??'Lunch'),(string)($r['quantity']??'')]);if($chk->fetchColumn())continue;$ins=$db->prepare('INSERT INTO lunches(user_id,lunch_date,food_item,quantity,notes,meal_type,meal_time,recorded_time,calories,protein,carbs,fat) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');$ins->execute([$uid,$date,$food,(string)($r['quantity']??''),(string)($r['notes']??''),(string)($r['meal_type']??'Lunch'),(string)($r['meal_time']??'12:00-13:00'),(string)($r['recorded_time']??''),nutritionNumber($r['calories']??0),nutritionNumber($r['protein']??0),nutritionNumber($r['carbs']??0),nutritionNumber($r['fat']??0)]);$added++;}
 foreach(($data['weights']??[]) as $r){$date=$r['weight_date']??'';$kg=is_numeric($r['weight_kg']??null)?(float)$r['weight_kg']:0;if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||$kg<20||$kg>400)continue;$chk=$db->prepare('SELECT id FROM weights WHERE user_id=? AND weight_date=? AND ABS(weight_kg-?)<0.001 LIMIT 1');$chk->execute([$uid,$date,$kg]);if($chk->fetchColumn())continue;$ins=$db->prepare('INSERT INTO weights(user_id,weight_kg,weight_date,notes,created_at) VALUES(?,?,?,?,?)');$ins->execute([$uid,$kg,$date,(string)($r['notes']??''),(string)($r['created_at']??date('Y-m-d H:i:s'))]);$weightsAdded++;}
 $message="Backup merged safely: $added food entries and $weightsAdded weight records added. Existing records were kept.";
 }catch(Throwable $e){$error='Unable to restore this backup: '.$e->getMessage();}}}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0f172a"><title>Backup & Restore</title><link rel="stylesheet" href="assets/app.css"></head><body><main class="container"><div class="top"><a href="health.php">← Health Dashboard</a><a href="index.php">🍽️ Food Log</a></div><section class="hero"><div class="eyebrow">Data protection</div><h1>☁️ Backup & Restore</h1><p>Download your personal backup or merge an earlier backup into this account.</p></section><?php if($message):?><div class="ok">✓ <?=h($message)?></div><?php endif;?><?php if($error):?><div class="error">⚠ <?=h($error)?></div><?php endif;?><section class="card"><h2>Download Backup</h2><p class="muted">The backup contains your profile details, food history, nutrition values and weight records.</p><a class="action primary" href="backup.php?action=download">⬇ Download Backup JSON</a></section><section class="card"><h2>Restore / Merge</h2><p class="muted">Importing does <strong>not</strong> delete existing records. Matching food entries and weight records are skipped to reduce duplicates.</p><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=h(csrfToken())?>"><label>Backup JSON file</label><input type="file" name="backup" accept="application/json,.json" required><button class="save">Merge Backup Safely</button></form></section></main></body></html>
