<?php
declare(strict_types=1); require __DIR__.'/auth.php'; requireLogin();
$format=strtolower(trim((string)($_GET['format']??'csv')));$start=trim((string)($_GET['start']??''));$end=trim((string)($_GET['end']??''));
function vd($v){$d=DateTime::createFromFormat('!Y-m-d',$v);return $d&&$d->format('Y-m-d')===$v;}function rd($v){$t=strtotime($v);return $t?date('d-m-Y',$t):$v;}function safe($v){$v=trim(str_replace(["\t","\r","\n"],' ',(string)$v));return $v!==''&&in_array($v[0],['=','+','-','@'],true)?"'".$v:$v;}
if(!in_array($format,['csv','xlsx'],true)||!vd($start)||!vd($end)||$start>$end){http_response_code(400);exit('Invalid export request.');}
$q=$db->prepare('SELECT lunch_date,meal_type,meal_time,recorded_time,food_item,quantity,notes FROM lunches WHERE user_id=? AND lunch_date BETWEEN ? AND ? ORDER BY lunch_date,meal_time,id');$q->execute([$_SESSION['user_id'],$start,$end]);$rows=$q->fetchAll();
$data=[['Date','Meal','Meal Time','Recorded Time','Food Item','Quantity','Notes']];foreach($rows as $r)$data[]=[rd($r['lunch_date']),safe($r['meal_type']),safe($r['meal_time']),safe($r['recorded_time']),safe($r['food_item']),safe($r['quantity']),safe($r['notes'])];
$base='food_report_'.rd($start).'_to_'.rd($end);
if($format==='csv'){header('Content-Type:text/csv; charset=UTF-8');header('Content-Disposition:attachment; filename="'.$base.'.csv"');header('X-Content-Type-Options:nosniff');$o=fopen('php://output','wb');fwrite($o,"\xEF\xBB\xBF");foreach($data as $r)fputcsv($o,$r);fclose($o);exit;}
// Lightweight real XLSX generator using ZIP's STORE method; no Composer required.
function zipStore($files){$local='';$central='';$offset=0;$now=getdate();$dt=(($now['hours']&31)<<11)|(($now['minutes']&63)<<5)|(int)($now['seconds']/2);$dd=(($now['year']-1980)<<9)|(($now['mon']&15)<<5)|($now['mday']&31);foreach($files as $name=>$c){$n=strlen($name);$s=strlen($c);$crc=crc32($c);if($crc<0)$crc+=4294967296;$lh=pack('VvvvvvVVVvv',0x04034b50,20,0,0,$dt,$dd,$crc,$s,$s,$n,0);$rec=$lh.$name.$c;$local.=$rec;$central.=pack('VvvvvvvVVVvvvvvVV',0x02014b50,20,20,0,0,$dt,$dd,$crc,$s,$s,$n,0,0,0,0,0,$offset).$name;$offset+=strlen($rec);}return $local.$central.pack('VvvvvVVv',0x06054b50,0,0,count($files),count($files),strlen($central),strlen($local),0);}
function xe($v){return htmlspecialchars((string)$v,ENT_XML1|ENT_COMPAT,'UTF-8');}$xml='<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>';$r=1;foreach($data as $row){$xml.='<row r="'.$r.'">';$c=0;foreach($row as $v){$c++;$col='';$n=$c;while($n){$n--; $col=chr(65+$n%26).$col;$n=intdiv($n,26);}$xml.='<c r="'.$col.$r.'" t="inlineStr"><is><t xml:space="preserve">'.xe($v).'</t></is></c>';}$xml.='</row>';$r++;}$xml.='</sheetData></worksheet>';
$files=['[Content_Types].xml'=>'<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>','_rels/.rels'=>'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>','xl/workbook.xml'=>'<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Food Log" sheetId="1" r:id="rId1"/></sheets></workbook>','xl/_rels/workbook.xml.rels'=>'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>','xl/worksheets/sheet1.xml'=>$xml];
$out=zipStore($files);header('Content-Type:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition:attachment; filename="'.$base.'.xlsx"');header('Content-Length:'.strlen($out));header('X-Content-Type-Options:nosniff');echo $out;
