<?php
require __DIR__.'/auth.php';requireLogin();
$user=currentUser();$uid=(int)$_SESSION['user_id'];$today=date('Y-m-d');$weekStart=date('Y-m-d',strtotime('monday this week'));$weekEnd=date('Y-m-d',strtotime('sunday this week'));
if($_SERVER['REQUEST_METHOD']==='POST'){verifyCsrf();$date=trim($_POST['weight_date']??'');$weight=is_numeric($_POST['weight_kg']??null)?(float)$_POST['weight_kg']:0;$notes=trim($_POST['weight_notes']??'');$d=DateTime::createFromFormat('Y-m-d',$date);if($d&&$d->format('Y-m-d')===$date&&$weight>=20&&$weight<=400&&mb_strlen($notes)<=250){$q=$db->prepare('INSERT INTO weights(user_id,weight_kg,weight_date,notes,created_at) VALUES(?,?,?,?,?)');$q->execute([$uid,$weight,$date,$notes,date('Y-m-d H:i:s')]);header('Location: health.php?weight_saved=1');exit;}}
$q=$db->prepare('SELECT COALESCE(SUM(calories),0) cal,COALESCE(SUM(protein),0) protein,COALESCE(SUM(carbs),0) carbs,COALESCE(SUM(fat),0) fat,COUNT(*) entries FROM lunches WHERE user_id=? AND lunch_date=?');$q->execute([$uid,$today]);$todayN=$q->fetch();
$q=$db->prepare('SELECT COALESCE(SUM(calories),0) cal,COALESCE(SUM(protein),0) protein,COALESCE(SUM(carbs),0) carbs,COALESCE(SUM(fat),0) fat,COUNT(DISTINCT lunch_date) days FROM lunches WHERE user_id=? AND lunch_date BETWEEN ? AND ?');$q->execute([$uid,$weekStart,$weekEnd]);$weekN=$q->fetch();
$q=$db->prepare('SELECT weight_kg,weight_date,notes FROM weights WHERE user_id=? ORDER BY weight_date DESC,id DESC LIMIT 12');$q->execute([$uid]);$weights=$q->fetchAll();$latest=$weights[0]['weight_kg']??null;$previous=$weights[1]['weight_kg']??null;$weightChange=($latest!==null&&$previous!==null)?$latest-$previous:null;
$q=$db->prepare('SELECT DISTINCT lunch_date FROM lunches WHERE user_id=? AND lunch_date<=? ORDER BY lunch_date DESC LIMIT 90');$q->execute([$uid,$today]);$loggedDates=array_column($q->fetchAll(),'lunch_date');$streak=0;$cursor=new DateTime($today);$set=array_flip($loggedDates);while(isset($set[$cursor->format('Y-m-d')])){$streak++;$cursor->modify('-1 day');}
$achievements=[];if($streak>=3)$achievements[]=['🔥','3-Day Streak'];if($streak>=7)$achievements[]=['🔥','7-Day Streak'];if(count($loggedDates)>=10)$achievements[]=['📅','10 Logged Days'];if(count($loggedDates)>=30)$achievements[]=['🏆','30 Logged Days'];if($todayN['protein']>=50)$achievements[]=['💪','Protein Goal Day'];if($todayN['entries']>=6)$achievements[]=['⭐','Six Meals Logged'];
$recommendations=[];if((float)$todayN['protein']<50)$recommendations[]='Add a protein-rich food such as eggs, fish, chicken, dal, milk or curd to your next meal.';if((float)$todayN['entries']<3)$recommendations[]='Your log is light today. Try recording each meal/snack to improve your weekly insights.';if((float)$todayN['cal']>0&&$todayN['cal']<1200)$recommendations[]='Your recorded calories are currently low; make sure your meals are adequate for your personal needs.';if(!$recommendations)$recommendations[]='Great logging today. Keep a balanced mix of protein, vegetables, fruits and staple foods.';
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0f172a"><title>My Health Dashboard</title><link rel="stylesheet" href="assets/app.css"><style>.health-hero{background:linear-gradient(135deg,#0f172a,#1d4ed8);color:#fff;border-radius:24px;padding:22px;margin-bottom:15px}.health-hero h1{margin:0}.health-hero p{color:#dbeafe;margin:5px 0 0}.health-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.metric{background:#fff;border:1px solid var(--line);border-radius:16px;padding:14px}.metric strong{display:block;font-size:22px}.metric span{font-size:11px;color:var(--muted)}.recommend{border-left:4px solid var(--primary);background:#eff6ff;padding:13px;border-radius:12px;margin:8px 0;font-size:12px}.ach{display:flex;gap:8px;flex-wrap:wrap}.ach span{background:#f8fafc;border:1px solid var(--line);padding:9px 11px;border-radius:12px;font-size:11px;font-weight:800}.weight-list{display:grid;gap:7px}.weight-row{display:flex;justify-content:space-between;padding:10px;border-bottom:1px solid var(--line);font-size:12px}.weight-row:last-child{border:0}@media(max-width:700px){.health-grid{grid-template-columns:1fr 1fr}}
</style></head><body><main class="container"><div class="top"><a href="index.php">← Dashboard</a><a href="profile.php">👤 Profile</a></div><section class="health-hero"><div class="eyebrow">Personalized health center</div><h1>🧠 My Health Dashboard</h1><p>Welcome <?=h($user['name'])?> · nutrition, progress, streaks and weekly insights.</p></section>
<?php if(isset($_GET['weight_saved'])):?><div class="ok">✓ Weight entry saved without changing your food records.</div><?php endif;?><section class="card"><div class="head"><div><h2>🥗 Today's Nutrition</h2><small><?=h(date('d-m-Y'))?></small></div></div><div class="health-grid"><div class="metric"><strong><?=number_format((float)$todayN['cal'],0)?></strong><span>Calories kcal</span></div><div class="metric"><strong><?=number_format((float)$todayN['protein'],1)?>g</strong><span>Protein</span></div><div class="metric"><strong><?=number_format((float)$todayN['carbs'],1)?>g</strong><span>Carbs</span></div><div class="metric"><strong><?=number_format((float)$todayN['fat'],1)?>g</strong><span>Fat</span></div></div><p class="muted">Nutrition values are optional. Existing entries remain valid and are treated as 0 until you add nutrition details.</p></section>
<section class="card"><div class="head"><h2>🤖 Smart Recommendations</h2></div><?php foreach($recommendations as $r):?><div class="recommend">💡 <?=h($r)?></div><?php endforeach;?></section>
<section class="card"><div class="head"><div><h2>📋 Weekly Health Summary</h2><small><?=h(date('d-m-Y',strtotime($weekStart)))?> → <?=h(date('d-m-Y',strtotime($weekEnd)))?></small></div></div><div class="health-grid"><div class="metric"><strong><?=number_format((float)$weekN['cal'],0)?></strong><span>Weekly kcal</span></div><div class="metric"><strong><?=number_format((float)$weekN['protein'],1)?>g</strong><span>Weekly protein</span></div><div class="metric"><strong><?=number_format((float)$weekN['days'],0)?>/7</strong><span>Days logged</span></div><div class="metric"><strong><?=$streak?></strong><span>Current streak</span></div></div></section>
<section class="card"><div class="head"><div><h2>⚖️ Weight Progress</h2><small>Track your own measurements over time.</small></div><?php if($latest!==null):?><span class="pill"><?=h(number_format((float)$latest,1))?> kg</span><?php endif;?></div><form method="post"><input type="hidden" name="csrf_token" value="<?=h(csrfToken())?>"><div class="grid"><div><label>Date</label><input type="date" name="weight_date" value="<?=h($today)?>" required></div><div><label>Weight (kg)</label><input type="number" name="weight_kg" min="20" max="400" step="0.1" required placeholder="e.g. 60.5"></div><div class="full"><label>Note</label><input name="weight_notes" maxlength="250" placeholder="Optional note"></div></div><button class="save">Add Weight</button></form><?php if($weightChange!==null):?><p class="muted" style="margin-top:12px">Latest change: <strong><?=($weightChange>0?'+':'').number_format($weightChange,1)?> kg</strong> compared with the previous record.</p><?php endif;?><?php if($weights):?><div class="weight-list" style="margin-top:12px"><?php foreach($weights as $w):?><div class="weight-row"><span><?=h(date('d-m-Y',strtotime($w['weight_date'])))?></span><strong><?=h(number_format((float)$w['weight_kg'],1))?> kg</strong></div><?php endforeach;?></div><?php endif;?></section>
<section class="card"><div class="head"><div><h2>🏆 Achievements</h2><small>Earned automatically from your log.</small></div></div><?php if($achievements):?><div class="ach"><?php foreach($achievements as $a):?><span><?=$a[0]?> <?=h($a[1])?></span><?php endforeach;?></div><?php else:?><p class="muted">Keep logging meals to unlock your first achievement.</p><?php endif;?></section>
<section class="card"><div class="head"><h2>☁️ Backup & Restore</h2></div><p class="muted">Create a personal backup of your food history and profile data. Restore uses a safe merge so existing entries are not intentionally deleted.</p><a class="action primary" href="backup.php?action=download">⬇ Download My Backup</a><a class="action" href="backup.php">Restore / Import Backup</a></section>
<section class="card"><div class="actions"><a class="action primary" href="reports.php">📊 Full Reports</a><a class="action" href="index.php">🍽️ Food Log</a><a class="action" href="profile.php">👤 Profile</a></div></section></main></body></html>
