<?php
require __DIR__.'/auth.php';
requireLogin();
$user=currentUser();
$today=date('Y-m-d');
$schedule=[
 ['08:00','09:00','Breakfast','Idli / dosa / chapati + egg','🍳'],
 ['10:30','11:00','Morning Snack','Banana or another fruit','🍌'],
 ['12:00','13:00','Lunch','Rice + vegetables + fish/chicken/egg/dal','🍚'],
 ['16:30','17:00','Evening Snack','Milk + guava + peanuts/almonds','🥛'],
 ['20:00','21:00','During Duty','2 boiled eggs + banana','🥚'],
 ['22:15','22:45','Dinner','Rice + fish/egg/chicken + vegetables','🍛']
];
$allowedMealNames=array_column($schedule,2);
$stmt=$db->prepare('SELECT id,lunch_date,food_item,quantity,notes,meal_type,meal_time,recorded_time FROM lunches WHERE user_id=? AND lunch_date=? ORDER BY meal_time ASC,id DESC');
$stmt->execute([$_SESSION['user_id'],$today]);$lunches=$stmt->fetchAll();
$stmt=$db->prepare('SELECT COUNT(*) FROM lunches WHERE user_id=?');$stmt->execute([$_SESSION['user_id']]);$totalAll=(int)$stmt->fetchColumn();
$stmt=$db->prepare('SELECT COUNT(DISTINCT lunch_date) FROM lunches WHERE user_id=?');$stmt->execute([$_SESSION['user_id']]);$daysLogged=(int)$stmt->fetchColumn();
$todayMeals=array_fill_keys($allowedMealNames,false);foreach($lunches as $row){$todayMeals[$row['meal_type']??'Lunch']=true;}
$completedMeals=count(array_filter($todayMeals));$mealProgress=(int)round(($completedMeals/count($allowedMealNames))*100);
function displayDate(string $iso):string{$t=strtotime($iso);return $t?date('d-m-Y',$t):$iso;}
function displayTime(?string $iso):string{$t=$iso?strtotime($iso):false;return $t?date('h:i A',$t):'';}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0f172a"><meta name="description" content="Personal meal tracker with food history, reports and meal reminders."><link rel="manifest" href="manifest.json"><link rel="icon" href="assets/icon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="assets/icon.svg"><link rel="stylesheet" href="assets/app.css"><title>Lunch Food Log</title><style>.hero-row{display:flex;align-items:center;gap:14px}.app-logo{width:70px;height:70px;border-radius:18px;box-shadow:0 8px 20px rgba(0,0,0,.25)}.progress{height:9px;background:#e5e7eb;border-radius:99px;overflow:hidden;margin-top:9px}.progress>span{display:block;height:100%;background:#2563eb;border-radius:99px}.meal.done{border-color:#bbf7d0;background:#f0fdf4}.done-mark{font-size:11px;color:#15803d;font-weight:900}.entry-actions form{margin:0}.logout-btn{width:auto!important;margin:0!important}.quick-note{font-size:12px;color:var(--muted);margin:0}.search-wrap{margin-bottom:12px}.search-wrap input{background:#f8fafc}.empty{padding:25px 10px}.mobile-nav{padding-bottom:calc(7px + env(safe-area-inset-bottom))}@media(max-width:600px){.hero-row{align-items:flex-start}.app-logo{width:58px;height:58px;border-radius:15px}.hero{padding:19px}.hero h1{font-size:25px}}</style></head><body>
<main class="container">
<header class="hero"><div class="hero-row"><img class="app-logo" src="assets/icon.svg" alt="Lunch Food Log app logo" width="70" height="70"><div><div class="eyebrow">Personal nutrition tracker</div><h1>Lunch Food Log</h1><p>Welcome, <?=h($user['name'])?>. Keep every meal organized.</p></div></div><div class="userbar"><span>👤 <?=h($user['email'])?></span><span><a href="profile.php">Profile</a> <form method="post" action="logout.php" style="display:inline"><input type="hidden" name="csrf_token" value="<?=h(csrfToken())?>"><button class="logout-btn" type="submit">Logout</button></form></span></div></header>
<?php if(isset($_GET['saved'])):?><div class="flash">✓ Food entry saved successfully.</div><?php elseif(isset($_GET['updated'])):?><div class="flash">✓ Food entry updated successfully.</div><?php elseif(isset($_GET['deleted'])):?><div class="flash">✓ Food entry deleted.</div><?php elseif(isset($_GET['welcome'])):?><div class="flash">✓ Account created. Your food log is ready.</div><?php elseif(isset($_GET['expired'])):?><div class="flash">Your session expired for security. Please log in again.</div><?php endif;?>
<section class="stats"><div class="stat"><strong><?=$completedMeals?>/6</strong><span>Meals logged today</span></div><div class="stat"><strong><?=$daysLogged?></strong><span>Days logged</span></div><div class="stat"><strong><?=$totalAll?></strong><span>Total entries</span></div></section>
<section class="card"><div class="head"><div><h2>📈 Today's Progress</h2><p class="quick-note">Keep your six meal windows on track.</p></div><span class="pill"><?=$mealProgress?>%</span></div><div class="progress" aria-label="<?=$mealProgress?> percent of meals logged"><span style="width:<?=$mealProgress?>%"></span></div></section>
<section class="card"><div class="head"><h2>⏰ Daily Food Timetable</h2><small>6 meal windows</small></div><div class="schedule"><?php foreach($schedule as $m):$done=!empty($todayMeals[$m[2]]);?><div class="meal <?=$done?'done':''?>"><div class="icon"><?=$m[4]?></div><div><div class="meal-name"><?=h($m[2])?> <?php if($done):?><span class="done-mark">✓ Logged</span><?php endif;?></div><div class="time"><?=date('h:i A',strtotime($m[0]))?> – <?=date('h:i A',strtotime($m[1]))?></div><div class="foodhint"><?=h($m[3])?></div></div></div><?php endforeach;?></div><button class="notify" id="mealNotifyButton" type="button" onclick="enableMealReminders();">🔔 Enable Meal Notifications</button><div class="help">PWA/browser reminders can alert you when the app is running or resumed.</div></section>
<section class="card"><div class="head"><h2>➕ Add Food Entry</h2><small>DD-MM-YYYY</small></div><form method="post" action="save.php" id="foodForm"><input type="hidden" name="csrf_token" value="<?=h(csrfToken())?>"><div class="grid"><div><label>Date</label><input id="date_display" value="<?=h(displayDate($today))?>" placeholder="DD-MM-YYYY" inputmode="numeric" maxlength="10" autocomplete="off" required><input type="hidden" name="lunch_date" id="lunch_date" value="<?=h($today)?>"></div><div><label>Meal</label><select name="meal_type"><?php foreach($schedule as $m):?><option value="<?=h($m[2])?>" <?=$m[2]==='Lunch'?'selected':''?>><?=$m[4].' '.h($m[2])?></option><?php endforeach;?></select></div><div class="full"><label>Food Item</label><input name="food_item" maxlength="150" placeholder="e.g. Rice + Fish Curry" autocomplete="off" required></div><div><label>Quantity</label><input name="quantity" maxlength="80" placeholder="e.g. 1 plate"></div><div><label>Notes</label><input name="notes" maxlength="250" placeholder="Optional note"></div></div><button class="save">Save Food Entry</button></form></section>
<section class="card"><div class="head"><div><h2>🍽️ Today's Entries</h2><p class="quick-note"><?=h(displayDate($today))?> · Search and manage your entries</p></div><span class="pill"><?=$totalAll?> total</span></div><?php if(!$lunches):?><div class="empty">No food entries recorded today.<br>Add your first meal above.</div><?php else:?><div class="search-wrap"><input type="search" id="foodSearch" placeholder="🔎 Search today's food, meal or notes..." aria-label="Search today's food"></div><div class="entries" id="foodEntries"><?php foreach($lunches as $item):?><article class="entry"><div class="entrytop"><div class="food"><?=h($item['food_item'])?></div><div class="badge"><?=h($item['meal_type']??'Lunch')?></div></div><div class="meta">📅 <?=h(displayDate($item['lunch_date']))?> · ⏰ <?=h($item['meal_time']??'')?> · <?=h(displayTime($item['recorded_time']??''))?></div><?php if($item['quantity']):?><div class="meta"><strong>Quantity:</strong> <?=h($item['quantity'])?></div><?php endif;?><?php if($item['notes']):?><div class="notes">📝 <?=h($item['notes'])?></div><?php endif;?><div class="entry-actions"><a class="edit" href="edit.php?id=<?=urlencode($item['id'])?>">Edit</a><form method="post" action="delete.php" onsubmit="return confirm('Delete this food entry?');"><input type="hidden" name="csrf_token" value="<?=h(csrfToken())?>"><input type="hidden" name="id" value="<?=h($item['id'])?>"><button class="delete" type="submit">Delete</button></form></div></article><?php endforeach;?></div><div id="noSearchResults" class="empty" style="display:none">No matching food entries found.</div><?php endif;?></section>
<section class="card"><div class="head"><h2>⚡ Quick Access</h2></div><div class="actions"><a class="action primary" href="reports.php">📊 Reports</a><a class="action" href="reports.php?report=monthly">📅 Monthly</a><a class="action" href="profile.php">👤 Profile</a></div></section>
<div class="footer">Lunch Food Log · Secure account system · DD-MM-YYYY · <?=date('Y')?></div></main>
<div id="mealAlertBanner" class="alert-banner"></div><script src="assets/meal-alert.js" defer></script><script>
function isoFromDisplay(v){const m=v.trim().match(/^(\d{2})-(\d{2})-(\d{4})$/);if(!m)return null;const d=+m[1],mo=+m[2],y=+m[3],x=new Date(Date.UTC(y,mo-1,d));return x.getUTCFullYear()===y&&x.getUTCMonth()===mo-1&&x.getUTCDate()===d?`${y}-${String(mo).padStart(2,'0')}-${String(d).padStart(2,'0')}`:null}
document.getElementById('foodForm').addEventListener('submit',e=>{const iso=isoFromDisplay(document.getElementById('date_display').value);if(!iso){e.preventDefault();alert('Please enter a valid date in DD-MM-YYYY format.');return}document.getElementById('lunch_date').value=iso});
const search=document.getElementById('foodSearch'),entries=document.querySelectorAll('#foodEntries .entry'),none=document.getElementById('noSearchResults');if(search)search.addEventListener('input',()=>{const q=search.value.trim().toLowerCase();let shown=0;entries.forEach(card=>{const hit=card.textContent.toLowerCase().includes(q);card.style.display=hit?'':'none';if(hit)shown++});if(none)none.style.display=shown?'none':''});
</script></body></html>
